import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  content: { flexGrow: 1, justifyContent: 'center', padding: 24 },
  disabledButton: { opacity: 0.45 },
  divider: { backgroundColor: '#27272a', flex: 1, height: 1 },
  dividerRow: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  dividerText: { color: '#71717a', fontSize: 12, fontWeight: '700' },
  errorPanel: {
    backgroundColor: '#2a1118',
    borderColor: '#7f1d35',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 20,
    padding: 12,
  },
  errorText: { color: '#fda4af', fontSize: 14, lineHeight: 20 },
  eyebrow: {
    color: '#a78bfa',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  field: { gap: 8 },
  footerLink: { color: '#c4b5fd', fontWeight: '700' },
  footerText: { color: '#a1a1aa', marginTop: 28, textAlign: 'center' },
  form: { gap: 16 },
  header: { gap: 10, marginBottom: 28 },
  input: {
    backgroundColor: '#111118',
    borderColor: '#3f3f46',
    borderRadius: 8,
    borderWidth: 1,
    color: '#f4f4f5',
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  keyboardView: { flex: 1 },
  label: { color: '#d4d4d8', fontSize: 14, fontWeight: '600' },
  noticePanel: {
    backgroundColor: '#10241d',
    borderColor: '#166534',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 20,
    padding: 12,
  },
  noticeText: { color: '#86efac', fontSize: 14, lineHeight: 20 },
  pressedButton: { transform: [{ scale: 0.99 }] },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#c4b5fd',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 52,
  },
  primaryButtonText: { color: '#18181b', fontSize: 16, fontWeight: '800' },
  safeArea: { backgroundColor: '#08080d', flex: 1 },
  secondaryButton: {
    alignItems: 'center',
    borderColor: '#52525b',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
  },
  secondaryButtonText: { color: '#f4f4f5', fontSize: 16, fontWeight: '700' },
  subtitle: { color: '#a1a1aa', fontSize: 16, lineHeight: 24 },
  title: {
    color: '#fafafa',
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
})
